# Generated by Django 4.2.28 on 2026-02-23 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("meeting", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="meetingroom",
            options={
                "ordering": ["name"],
                "verbose_name": "Meeting Room",
                "verbose_name_plural": "Meeting Rooms",
            },
        ),
        migrations.AlterModelOptions(
            name="roombooking",
            options={
                "ordering": ["-start_at"],
                "verbose_name": "Room Booking",
                "verbose_name_plural": "Room Bookings",
            },
        ),
        migrations.AlterField(
            model_name="meetingroom",
            name="capacity",
            field=models.PositiveIntegerField(default=0, verbose_name="Capacity"),
        ),
        migrations.AlterField(
            model_name="meetingroom",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="meetingroom",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="meetingroom",
            name="location",
            field=models.CharField(blank=True, max_length=200, verbose_name="Location"),
        ),
        migrations.AlterField(
            model_name="meetingroom",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Room Name"
            ),
        ),
        migrations.AlterField(
            model_name="roombooking",
            name="canceled_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Canceled At"
            ),
        ),
        migrations.AlterField(
            model_name="roombooking",
            name="end_at",
            field=models.DateTimeField(verbose_name="End Time"),
        ),
        migrations.AlterField(
            model_name="roombooking",
            name="organizer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="room_bookings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Organizer",
            ),
        ),
        migrations.AlterField(
            model_name="roombooking",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="meeting.meetingroom",
                verbose_name="Meeting Room",
            ),
        ),
        migrations.AlterField(
            model_name="roombooking",
            name="start_at",
            field=models.DateTimeField(verbose_name="Start Time"),
        ),
        migrations.AlterField(
            model_name="roombooking",
            name="status",
            field=models.CharField(
                choices=[("booked", "Booked"), ("canceled", "Canceled")],
                default="booked",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="roombooking",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Title"),
        ),
    ]
