# Generated by Django 4.2.28 on 2026-04-24 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "meeting",
            "0002_alter_meetingroom_options_alter_roombooking_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="roombooking",
            name="guest_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Guest Count"),
        ),
        migrations.AddField(
            model_name="roombooking",
            name="remarks",
            field=models.TextField(
                blank=True,
                help_text="E.g., laptops or certain devices required",
                verbose_name="Remarks",
            ),
        ),
    ]
