# Generated by Django 4.2.28 on 2026-02-23 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("admin_office", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notice",
            options={
                "ordering": ["-published_at"],
                "verbose_name": "Notice",
                "verbose_name_plural": "Notices",
            },
        ),
        migrations.AlterField(
            model_name="notice",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Author",
            ),
        ),
        migrations.AlterField(
            model_name="notice",
            name="content",
            field=models.TextField(verbose_name="Content"),
        ),
        migrations.AlterField(
            model_name="notice",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="Published"),
        ),
        migrations.AlterField(
            model_name="notice",
            name="published_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Published At"),
        ),
        migrations.AlterField(
            model_name="notice",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Title"),
        ),
    ]
