# Generated by Django 4.2.28 on 2026-02-23 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("docs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Document",
                "verbose_name_plural": "Document Management",
            },
        ),
        migrations.AlterField(
            model_name="document",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(upload_to="docs/%Y/%m/", verbose_name="File"),
        ),
        migrations.AlterField(
            model_name="document",
            name="is_public",
            field=models.BooleanField(default=True, verbose_name="Public"),
        ),
        migrations.AlterField(
            model_name="document",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="document",
            name="uploader",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Uploader",
            ),
        ),
    ]
