# Generated by Django 4.2.28 on 2026-02-23 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReimbursementRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="E.g., Business Trip to Tokyo",
                        max_length=200,
                        verbose_name="Title",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("PAID", "Paid"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="Rejection Reason"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_reimbursements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approver",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reimbursements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Requester",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reimbursement Request",
                "verbose_name_plural": "Reimbursement Requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExpenseItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expense_date", models.DateField(verbose_name="Date of Expense")),
                (
                    "expense_type",
                    models.CharField(
                        choices=[
                            ("HOTEL", "Hotel"),
                            ("DINING", "Dining"),
                            ("TRAVEL", "Travel"),
                            ("MISC", "Miscellaneous"),
                        ],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Amount"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("HKD", "HKD"),
                            ("USD", "USD"),
                            ("CNY", "CNY"),
                            ("EUR", "EUR"),
                            ("GBP", "GBP"),
                            ("JPY", "JPY"),
                            ("OTHER", "Other"),
                        ],
                        default="HKD",
                        max_length=10,
                        verbose_name="Currency",
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=1.0,
                        help_text="Exchange rate to HKD (Base Currency)",
                        max_digits=10,
                        verbose_name="Exchange Rate",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Description"
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="finance/receipts/%Y/%m/",
                        verbose_name="Receipt/Invoice",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="finance.reimbursementrequest",
                        verbose_name="Reimbursement Request",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expense Item",
                "verbose_name_plural": "Expense Items",
                "ordering": ["expense_date"],
            },
        ),
    ]
