# Generated by Django 4.2.28 on 2026-02-23 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reimbursementrequest",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("can_check_reimbursement", "Can check reimbursement requests")
                ],
                "verbose_name": "Reimbursement Request",
                "verbose_name_plural": "Reimbursement Requests",
            },
        ),
        migrations.AddField(
            model_name="reimbursementrequest",
            name="checked_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Checked At"
            ),
        ),
        migrations.AddField(
            model_name="reimbursementrequest",
            name="checker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="checked_reimbursements",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Checker",
            ),
        ),
        migrations.AlterField(
            model_name="reimbursementrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("SUBMITTED", "Submitted"),
                    ("CHECKED", "Checked"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("PAID", "Paid"),
                ],
                default="DRAFT",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
