# Generated by Django 4.2.30 on 2026-08-30 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_department_options_alter_user_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="can_approve_all_leaves",
            field=models.BooleanField(
                default=False,
                help_text="Global approver: appears in every employee's approver picker and can approve all leave applications.",
                verbose_name="Can Approve All Leaves",
            ),
        ),
    ]
