# Generated by Django 4.2.28 on 2026-02-23 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hr", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="leaveapplication",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Leave Application",
                "verbose_name_plural": "Leave Applications",
            },
        ),
        migrations.AlterField(
            model_name="leaveapplication",
            name="applicant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leave_applications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Applicant",
            ),
        ),
        migrations.AlterField(
            model_name="leaveapplication",
            name="end_date",
            field=models.DateField(verbose_name="End Date"),
        ),
        migrations.AlterField(
            model_name="leaveapplication",
            name="leave_type",
            field=models.CharField(
                choices=[
                    ("sick", "Sick Leave"),
                    ("annual", "Annual Leave"),
                    ("personal", "Personal Leave"),
                    ("birthday", "Birthday Leave"),
                    ("maternity", "Maternity Leave"),
                    ("paternity", "Paternity Leave"),
                    ("compassionate", "Compassionate Leave"),
                    ("no_pay", "No Pay Leave"),
                ],
                default="sick",
                max_length=20,
                verbose_name="Leave Type",
            ),
        ),
        migrations.AlterField(
            model_name="leaveapplication",
            name="reason",
            field=models.TextField(verbose_name="Reason"),
        ),
        migrations.AlterField(
            model_name="leaveapplication",
            name="reviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leaves_to_review",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Reviewer",
            ),
        ),
        migrations.AlterField(
            model_name="leaveapplication",
            name="start_date",
            field=models.DateField(verbose_name="Start Date"),
        ),
        migrations.AlterField(
            model_name="leaveapplication",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="draft",
                max_length=50,
                protected=True,
                verbose_name="Status",
            ),
        ),
        migrations.CreateModel(
            name="LeaveApplicationDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dates",
                        to="hr.leaveapplication",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
            },
        ),
    ]
