# Generated by Django 4.2.28 on 2026-04-24 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0002_alter_leaveapplication_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaveapplication",
            name="is_half_day",
            field=models.BooleanField(default=False, verbose_name="Half Day"),
        ),
        migrations.AlterField(
            model_name="leaveapplication",
            name="leave_type",
            field=models.CharField(
                choices=[
                    ("sick", "Sick Leave"),
                    ("annual", "Annual Leave"),
                    ("birthday", "Birthday Leave"),
                    ("maternity", "Maternity Leave"),
                    ("paternity", "Paternity Leave"),
                    ("compassionate", "Compassionate Leave"),
                    ("no_pay", "No Pay Leave"),
                ],
                default="sick",
                max_length=20,
                verbose_name="Leave Type",
            ),
        ),
    ]
