# Generated by Django 4.2.28 on 2026-06-01 07:36

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0003_leaveapplication_is_half_day_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaveapplication",
            name="half_day_period",
            field=models.CharField(
                blank=True,
                choices=[("am", "AM"), ("pm", "PM")],
                max_length=2,
                null=True,
                verbose_name="Half Day Period",
            ),
        ),
        migrations.AlterField(
            model_name="leaveapplication",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("withdrawn", "Withdrawn"),
                ],
                default="draft",
                max_length=50,
                protected=True,
                verbose_name="Status",
            ),
        ),
    ]
