# Generated by Django 4.2.30 on 2026-08-30 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hr", "0004_leaveapplication_half_day_period_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaveapplication",
            name="approver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leaves_to_approve",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Approver",
            ),
        ),
        migrations.CreateModel(
            name="LeaveQuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(verbose_name="Year")),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("sick", "Sick Leave"),
                            ("annual", "Annual Leave"),
                            ("birthday", "Birthday Leave"),
                            ("maternity", "Maternity Leave"),
                            ("paternity", "Paternity Leave"),
                            ("compassionate", "Compassionate Leave"),
                            ("no_pay", "No Pay Leave"),
                        ],
                        default="annual",
                        max_length=20,
                        verbose_name="Leave Type",
                    ),
                ),
                (
                    "total_days",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Leave entitlement for the year (half days allowed).",
                        max_digits=4,
                        verbose_name="Total Days",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_quotas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leave Quota",
                "verbose_name_plural": "Leave Quotas",
                "ordering": ["user", "-year"],
            },
        ),
        migrations.AddConstraint(
            model_name="leavequota",
            constraint=models.UniqueConstraint(
                fields=("user", "year", "leave_type"),
                name="unique_user_year_type_quota",
            ),
        ),
    ]
