# Generated by Django 4.2.30 on 2026-08-31 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hr", "0006_backfill_approver_from_reviewer"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveApproverSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approvers",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Users this employee can pick as approver. Replaces the default department-head routing. Leave empty to allow only global approvers. Global approvers (Can Approve All Leaves) are always eligible and do not need to be listed here.",
                        related_name="leave_approver_settings_for",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Eligible Approvers",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_approver_setting",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leave Approver Setting",
                "verbose_name_plural": "Leave Approver Settings",
            },
        ),
    ]
