# Generated by Django 4.2.30 on 2026-10-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0007_leaveapproversetting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaveapplication",
            name="leave_type",
            field=models.CharField(
                choices=[
                    ("sick", "Sick Leave"),
                    ("annual", "Annual Leave"),
                    ("birthday", "Birthday Leave"),
                    ("maternity", "Maternity Leave"),
                    ("paternity", "Paternity Leave"),
                    ("compassionate", "Compassionate Leave"),
                    ("no_pay", "No Pay Leave"),
                    ("business_trip", "Business Trip"),
                ],
                default="sick",
                max_length=20,
                verbose_name="Leave Type",
            ),
        ),
        migrations.AlterField(
            model_name="leavequota",
            name="leave_type",
            field=models.CharField(
                choices=[
                    ("sick", "Sick Leave"),
                    ("annual", "Annual Leave"),
                    ("birthday", "Birthday Leave"),
                    ("maternity", "Maternity Leave"),
                    ("paternity", "Paternity Leave"),
                    ("compassionate", "Compassionate Leave"),
                    ("no_pay", "No Pay Leave"),
                    ("business_trip", "Business Trip"),
                ],
                default="annual",
                max_length=20,
                verbose_name="Leave Type",
            ),
        ),
    ]
